version: '3.9'

services:
# Versión de la sintaxis de Docker Compose
  api_gateway:
 
# Definición de todos los servicios y bases de datos para la arquitectura Strangler PoC
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - usuarios_service
      - pedidos_service
      - productos_service

  usuarios_service:
# Microservicio de usuarios
    build: ./usuarios_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@usuarios_db:5432/usuarios
    depends_on:
      - usuarios_db

  pedidos_service:
# Microservicio de pedidos
    build: ./pedidos_service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@pedidos_db:5432/pedidos
    depends_on:
      - pedidos_db

  productos_service:
# Microservicio de productos
    build: ./productos_service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@productos_db:5432/productos
    depends_on:
      - productos_db

  usuarios_db:
# Base de datos PostgreSQL para usuarios
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: usuarios
    ports:
      - "5433:5432"

  pedidos_db:
# Base de datos PostgreSQL para pedidos
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pedidos
    ports:
      - "5434:5432"

  productos_db:
# Base de datos PostgreSQL para productos
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: productos
    ports:
      - "5435:5432"
